services:
  postgres:
    container_name: postgres
    image: postgres:16.2
    env_file:
      - .env.prod
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d master"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.24.2
    container_name: goose-migrations
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.prod
    volumes:
      - ./migrations/postgres/master:/migrations
    restart: "no"

  service:
    container_name: orders-service
    build: .
    ports:
      - "8081:8081"
    env_file:
      - .env.prod
    depends_on:
      migrations:
        condition: service_completed_successfully
    environment:
      env: prod
    restart: unless-stopped

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter
    env_file:
      - .env.prod
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.prod.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  pgdata:
  grafana-data:
