[env]
_.file = '.env'
APP_ENV = "dev"
DB_USER = "postgres"
DB_NAME = "master"

[tools]
"go:github.com/pressly/goose/v3/cmd/goose" = "latest"
gofumpt = "latest"
golangci-lint = "v2.10.1"

[tasks.fmt]
run = "gofumpt -w -l ."

[tasks.lint]
run = "golangci-lint run"

[tasks.test]
run = "go test -v ./..."

[tasks.start]
run = "go run cmd/service/main.go"

[tasks.check]
depends = ["fmt", "lint"]

[tasks.migrate]
run = "goose postgres $DB_URL -dir migrations/postgres/master up"

[tasks.down]
run = "goose postgres $DB_URL -dir migrations/postgres/master down"
