// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"iTcatt/orders/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockimageRepo creates a new instance of MockimageRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockimageRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockimageRepo {
	mock := &MockimageRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockimageRepo is an autogenerated mock type for the imageRepo type
type MockimageRepo struct {
	mock.Mock
}

type MockimageRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockimageRepo) EXPECT() *MockimageRepo_Expecter {
	return &MockimageRepo_Expecter{mock: &_m.Mock}
}

// GetByProductID provides a mock function for the type MockimageRepo
func (_mock *MockimageRepo) GetByProductID(ctx context.Context, productID string) ([]models.Image, error) {
	ret := _mock.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetByProductID")
	}

	var r0 []models.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]models.Image, error)); ok {
		return returnFunc(ctx, productID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []models.Image); ok {
		r0 = returnFunc(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockimageRepo_GetByProductID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByProductID'
type MockimageRepo_GetByProductID_Call struct {
	*mock.Call
}

// GetByProductID is a helper method to define mock.On call
//   - ctx context.Context
//   - productID string
func (_e *MockimageRepo_Expecter) GetByProductID(ctx interface{}, productID interface{}) *MockimageRepo_GetByProductID_Call {
	return &MockimageRepo_GetByProductID_Call{Call: _e.mock.On("GetByProductID", ctx, productID)}
}

func (_c *MockimageRepo_GetByProductID_Call) Run(run func(ctx context.Context, productID string)) *MockimageRepo_GetByProductID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockimageRepo_GetByProductID_Call) Return(images []models.Image, err error) *MockimageRepo_GetByProductID_Call {
	_c.Call.Return(images, err)
	return _c
}

func (_c *MockimageRepo_GetByProductID_Call) RunAndReturn(run func(ctx context.Context, productID string) ([]models.Image, error)) *MockimageRepo_GetByProductID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByProductIDs provides a mock function for the type MockimageRepo
func (_mock *MockimageRepo) GetByProductIDs(ctx context.Context, productIDs []string) ([]models.Image, error) {
	ret := _mock.Called(ctx, productIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetByProductIDs")
	}

	var r0 []models.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]models.Image, error)); ok {
		return returnFunc(ctx, productIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []models.Image); ok {
		r0 = returnFunc(ctx, productIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, productIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockimageRepo_GetByProductIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByProductIDs'
type MockimageRepo_GetByProductIDs_Call struct {
	*mock.Call
}

// GetByProductIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - productIDs []string
func (_e *MockimageRepo_Expecter) GetByProductIDs(ctx interface{}, productIDs interface{}) *MockimageRepo_GetByProductIDs_Call {
	return &MockimageRepo_GetByProductIDs_Call{Call: _e.mock.On("GetByProductIDs", ctx, productIDs)}
}

func (_c *MockimageRepo_GetByProductIDs_Call) Run(run func(ctx context.Context, productIDs []string)) *MockimageRepo_GetByProductIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockimageRepo_GetByProductIDs_Call) Return(images []models.Image, err error) *MockimageRepo_GetByProductIDs_Call {
	_c.Call.Return(images, err)
	return _c
}

func (_c *MockimageRepo_GetByProductIDs_Call) RunAndReturn(run func(ctx context.Context, productIDs []string) ([]models.Image, error)) *MockimageRepo_GetByProductIDs_Call {
	_c.Call.Return(run)
	return _c
}
