// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"iTcatt/orders/internal/models"
	"iTcatt/orders/internal/storage"

	mock "github.com/stretchr/testify/mock"
)

// NewMockproductRepo creates a new instance of MockproductRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockproductRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockproductRepo {
	mock := &MockproductRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockproductRepo is an autogenerated mock type for the productRepo type
type MockproductRepo struct {
	mock.Mock
}

type MockproductRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockproductRepo) EXPECT() *MockproductRepo_Expecter {
	return &MockproductRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockproductRepo
func (_mock *MockproductRepo) Create(ctx context.Context, product models.Product) error {
	ret := _mock.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Product) error); ok {
		r0 = returnFunc(ctx, product)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockproductRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockproductRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - product models.Product
func (_e *MockproductRepo_Expecter) Create(ctx interface{}, product interface{}) *MockproductRepo_Create_Call {
	return &MockproductRepo_Create_Call{Call: _e.mock.On("Create", ctx, product)}
}

func (_c *MockproductRepo_Create_Call) Run(run func(ctx context.Context, product models.Product)) *MockproductRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Product
		if args[1] != nil {
			arg1 = args[1].(models.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockproductRepo_Create_Call) Return(err error) *MockproductRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockproductRepo_Create_Call) RunAndReturn(run func(ctx context.Context, product models.Product) error) *MockproductRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockproductRepo
func (_mock *MockproductRepo) Delete(ctx context.Context, id uint32) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockproductRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockproductRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint32
func (_e *MockproductRepo_Expecter) Delete(ctx interface{}, id interface{}) *MockproductRepo_Delete_Call {
	return &MockproductRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockproductRepo_Delete_Call) Run(run func(ctx context.Context, id uint32)) *MockproductRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockproductRepo_Delete_Call) Return(err error) *MockproductRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockproductRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, id uint32) error) *MockproductRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockproductRepo
func (_mock *MockproductRepo) Get(ctx context.Context, in storage.GetProductsIn) ([]models.Product, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []models.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.GetProductsIn) ([]models.Product, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, storage.GetProductsIn) []models.Product); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, storage.GetProductsIn) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockproductRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockproductRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - in storage.GetProductsIn
func (_e *MockproductRepo_Expecter) Get(ctx interface{}, in interface{}) *MockproductRepo_Get_Call {
	return &MockproductRepo_Get_Call{Call: _e.mock.On("Get", ctx, in)}
}

func (_c *MockproductRepo_Get_Call) Run(run func(ctx context.Context, in storage.GetProductsIn)) *MockproductRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 storage.GetProductsIn
		if args[1] != nil {
			arg1 = args[1].(storage.GetProductsIn)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockproductRepo_Get_Call) Return(products []models.Product, err error) *MockproductRepo_Get_Call {
	_c.Call.Return(products, err)
	return _c
}

func (_c *MockproductRepo_Get_Call) RunAndReturn(run func(ctx context.Context, in storage.GetProductsIn) ([]models.Product, error)) *MockproductRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockproductRepo
func (_mock *MockproductRepo) GetByID(ctx context.Context, id uint32) (models.Product, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32) (models.Product, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32) models.Product); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Product)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockproductRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockproductRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint32
func (_e *MockproductRepo_Expecter) GetByID(ctx interface{}, id interface{}) *MockproductRepo_GetByID_Call {
	return &MockproductRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockproductRepo_GetByID_Call) Run(run func(ctx context.Context, id uint32)) *MockproductRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockproductRepo_GetByID_Call) Return(product models.Product, err error) *MockproductRepo_GetByID_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockproductRepo_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uint32) (models.Product, error)) *MockproductRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockproductRepo
func (_mock *MockproductRepo) Update(ctx context.Context, id uint32, in storage.UpdateProductIn) error {
	ret := _mock.Called(ctx, id, in)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32, storage.UpdateProductIn) error); ok {
		r0 = returnFunc(ctx, id, in)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockproductRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockproductRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint32
//   - in storage.UpdateProductIn
func (_e *MockproductRepo_Expecter) Update(ctx interface{}, id interface{}, in interface{}) *MockproductRepo_Update_Call {
	return &MockproductRepo_Update_Call{Call: _e.mock.On("Update", ctx, id, in)}
}

func (_c *MockproductRepo_Update_Call) Run(run func(ctx context.Context, id uint32, in storage.UpdateProductIn)) *MockproductRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		var arg2 storage.UpdateProductIn
		if args[2] != nil {
			arg2 = args[2].(storage.UpdateProductIn)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockproductRepo_Update_Call) Return(err error) *MockproductRepo_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockproductRepo_Update_Call) RunAndReturn(run func(ctx context.Context, id uint32, in storage.UpdateProductIn) error) *MockproductRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}
