// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"iTcatt/orders/internal/models"
	"iTcatt/orders/internal/usecase"

	mock "github.com/stretchr/testify/mock"
)

// NewMockimageUsecase creates a new instance of MockimageUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockimageUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockimageUsecase {
	mock := &MockimageUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockimageUsecase is an autogenerated mock type for the imageUsecase type
type MockimageUsecase struct {
	mock.Mock
}

type MockimageUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockimageUsecase) EXPECT() *MockimageUsecase_Expecter {
	return &MockimageUsecase_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockimageUsecase
func (_mock *MockimageUsecase) Delete(ctx context.Context, imageID string) error {
	ret := _mock.Called(ctx, imageID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, imageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockimageUsecase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockimageUsecase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID string
func (_e *MockimageUsecase_Expecter) Delete(ctx interface{}, imageID interface{}) *MockimageUsecase_Delete_Call {
	return &MockimageUsecase_Delete_Call{Call: _e.mock.On("Delete", ctx, imageID)}
}

func (_c *MockimageUsecase_Delete_Call) Run(run func(ctx context.Context, imageID string)) *MockimageUsecase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockimageUsecase_Delete_Call) Return(err error) *MockimageUsecase_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockimageUsecase_Delete_Call) RunAndReturn(run func(ctx context.Context, imageID string) error) *MockimageUsecase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type MockimageUsecase
func (_mock *MockimageUsecase) Upload(ctx context.Context, input usecase.UploadImageIn) (models.Image, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 models.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.UploadImageIn) (models.Image, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.UploadImageIn) models.Image); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(models.Image)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, usecase.UploadImageIn) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockimageUsecase_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockimageUsecase_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.UploadImageIn
func (_e *MockimageUsecase_Expecter) Upload(ctx interface{}, input interface{}) *MockimageUsecase_Upload_Call {
	return &MockimageUsecase_Upload_Call{Call: _e.mock.On("Upload", ctx, input)}
}

func (_c *MockimageUsecase_Upload_Call) Run(run func(ctx context.Context, input usecase.UploadImageIn)) *MockimageUsecase_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecase.UploadImageIn
		if args[1] != nil {
			arg1 = args[1].(usecase.UploadImageIn)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockimageUsecase_Upload_Call) Return(image models.Image, err error) *MockimageUsecase_Upload_Call {
	_c.Call.Return(image, err)
	return _c
}

func (_c *MockimageUsecase_Upload_Call) RunAndReturn(run func(ctx context.Context, input usecase.UploadImageIn) (models.Image, error)) *MockimageUsecase_Upload_Call {
	_c.Call.Return(run)
	return _c
}
