// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"iTcatt/orders/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockcategoryRepo creates a new instance of MockcategoryRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockcategoryRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockcategoryRepo {
	mock := &MockcategoryRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockcategoryRepo is an autogenerated mock type for the categoryRepo type
type MockcategoryRepo struct {
	mock.Mock
}

type MockcategoryRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockcategoryRepo) EXPECT() *MockcategoryRepo_Expecter {
	return &MockcategoryRepo_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function for the type MockcategoryRepo
func (_mock *MockcategoryRepo) GetAll(ctx context.Context) ([]models.Category, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Category, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Category); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockcategoryRepo_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockcategoryRepo_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockcategoryRepo_Expecter) GetAll(ctx interface{}) *MockcategoryRepo_GetAll_Call {
	return &MockcategoryRepo_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockcategoryRepo_GetAll_Call) Run(run func(ctx context.Context)) *MockcategoryRepo_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockcategoryRepo_GetAll_Call) Return(categorys []models.Category, err error) *MockcategoryRepo_GetAll_Call {
	_c.Call.Return(categorys, err)
	return _c
}

func (_c *MockcategoryRepo_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]models.Category, error)) *MockcategoryRepo_GetAll_Call {
	_c.Call.Return(run)
	return _c
}
