// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockproductHandler creates a new instance of MockproductHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockproductHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockproductHandler {
	mock := &MockproductHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockproductHandler is an autogenerated mock type for the productHandler type
type MockproductHandler struct {
	mock.Mock
}

type MockproductHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockproductHandler) EXPECT() *MockproductHandler_Expecter {
	return &MockproductHandler_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockproductHandler
func (_mock *MockproductHandler) Create(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockproductHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockproductHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockproductHandler_Expecter) Create(w interface{}, r interface{}) *MockproductHandler_Create_Call {
	return &MockproductHandler_Create_Call{Call: _e.mock.On("Create", w, r)}
}

func (_c *MockproductHandler_Create_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockproductHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockproductHandler_Create_Call) Return() *MockproductHandler_Create_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockproductHandler_Create_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockproductHandler_Create_Call {
	_c.Run(run)
	return _c
}

// Delete provides a mock function for the type MockproductHandler
func (_mock *MockproductHandler) Delete(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockproductHandler_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockproductHandler_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockproductHandler_Expecter) Delete(w interface{}, r interface{}) *MockproductHandler_Delete_Call {
	return &MockproductHandler_Delete_Call{Call: _e.mock.On("Delete", w, r)}
}

func (_c *MockproductHandler_Delete_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockproductHandler_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockproductHandler_Delete_Call) Return() *MockproductHandler_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockproductHandler_Delete_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockproductHandler_Delete_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockproductHandler
func (_mock *MockproductHandler) Get(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockproductHandler_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockproductHandler_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockproductHandler_Expecter) Get(w interface{}, r interface{}) *MockproductHandler_Get_Call {
	return &MockproductHandler_Get_Call{Call: _e.mock.On("Get", w, r)}
}

func (_c *MockproductHandler_Get_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockproductHandler_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockproductHandler_Get_Call) Return() *MockproductHandler_Get_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockproductHandler_Get_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockproductHandler_Get_Call {
	_c.Run(run)
	return _c
}

// GetByID provides a mock function for the type MockproductHandler
func (_mock *MockproductHandler) GetByID(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockproductHandler_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockproductHandler_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockproductHandler_Expecter) GetByID(w interface{}, r interface{}) *MockproductHandler_GetByID_Call {
	return &MockproductHandler_GetByID_Call{Call: _e.mock.On("GetByID", w, r)}
}

func (_c *MockproductHandler_GetByID_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockproductHandler_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockproductHandler_GetByID_Call) Return() *MockproductHandler_GetByID_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockproductHandler_GetByID_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockproductHandler_GetByID_Call {
	_c.Run(run)
	return _c
}

// Update provides a mock function for the type MockproductHandler
func (_mock *MockproductHandler) Update(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockproductHandler_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockproductHandler_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockproductHandler_Expecter) Update(w interface{}, r interface{}) *MockproductHandler_Update_Call {
	return &MockproductHandler_Update_Call{Call: _e.mock.On("Update", w, r)}
}

func (_c *MockproductHandler_Update_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockproductHandler_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockproductHandler_Update_Call) Return() *MockproductHandler_Update_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockproductHandler_Update_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockproductHandler_Update_Call {
	_c.Run(run)
	return _c
}
