// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockcategoryHandler creates a new instance of MockcategoryHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockcategoryHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockcategoryHandler {
	mock := &MockcategoryHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockcategoryHandler is an autogenerated mock type for the categoryHandler type
type MockcategoryHandler struct {
	mock.Mock
}

type MockcategoryHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockcategoryHandler) EXPECT() *MockcategoryHandler_Expecter {
	return &MockcategoryHandler_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockcategoryHandler
func (_mock *MockcategoryHandler) Get(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockcategoryHandler_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockcategoryHandler_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockcategoryHandler_Expecter) Get(w interface{}, r interface{}) *MockcategoryHandler_Get_Call {
	return &MockcategoryHandler_Get_Call{Call: _e.mock.On("Get", w, r)}
}

func (_c *MockcategoryHandler_Get_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockcategoryHandler_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockcategoryHandler_Get_Call) Return() *MockcategoryHandler_Get_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockcategoryHandler_Get_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockcategoryHandler_Get_Call {
	_c.Run(run)
	return _c
}
