// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockimageHandler creates a new instance of MockimageHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockimageHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockimageHandler {
	mock := &MockimageHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockimageHandler is an autogenerated mock type for the imageHandler type
type MockimageHandler struct {
	mock.Mock
}

type MockimageHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockimageHandler) EXPECT() *MockimageHandler_Expecter {
	return &MockimageHandler_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockimageHandler
func (_mock *MockimageHandler) Delete(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockimageHandler_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockimageHandler_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockimageHandler_Expecter) Delete(w interface{}, r interface{}) *MockimageHandler_Delete_Call {
	return &MockimageHandler_Delete_Call{Call: _e.mock.On("Delete", w, r)}
}

func (_c *MockimageHandler_Delete_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockimageHandler_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockimageHandler_Delete_Call) Return() *MockimageHandler_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockimageHandler_Delete_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockimageHandler_Delete_Call {
	_c.Run(run)
	return _c
}

// Reorder provides a mock function for the type MockimageHandler
func (_mock *MockimageHandler) Reorder(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockimageHandler_Reorder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reorder'
type MockimageHandler_Reorder_Call struct {
	*mock.Call
}

// Reorder is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockimageHandler_Expecter) Reorder(w interface{}, r interface{}) *MockimageHandler_Reorder_Call {
	return &MockimageHandler_Reorder_Call{Call: _e.mock.On("Reorder", w, r)}
}

func (_c *MockimageHandler_Reorder_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockimageHandler_Reorder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockimageHandler_Reorder_Call) Return() *MockimageHandler_Reorder_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockimageHandler_Reorder_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockimageHandler_Reorder_Call {
	_c.Run(run)
	return _c
}

// Upload provides a mock function for the type MockimageHandler
func (_mock *MockimageHandler) Upload(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockimageHandler_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockimageHandler_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockimageHandler_Expecter) Upload(w interface{}, r interface{}) *MockimageHandler_Upload_Call {
	return &MockimageHandler_Upload_Call{Call: _e.mock.On("Upload", w, r)}
}

func (_c *MockimageHandler_Upload_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockimageHandler_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockimageHandler_Upload_Call) Return() *MockimageHandler_Upload_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockimageHandler_Upload_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockimageHandler_Upload_Call {
	_c.Run(run)
	return _c
}
