// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"iTcatt/orders/internal/models"
	"iTcatt/orders/internal/usecase"

	mock "github.com/stretchr/testify/mock"
)

// NewMockproductUsecase creates a new instance of MockproductUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockproductUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockproductUsecase {
	mock := &MockproductUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockproductUsecase is an autogenerated mock type for the productUsecase type
type MockproductUsecase struct {
	mock.Mock
}

type MockproductUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockproductUsecase) EXPECT() *MockproductUsecase_Expecter {
	return &MockproductUsecase_Expecter{mock: &_m.Mock}
}

// CreateProduct provides a mock function for the type MockproductUsecase
func (_mock *MockproductUsecase) CreateProduct(ctx context.Context, in usecase.CreateProductIn) (uint32, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 uint32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.CreateProductIn) (uint32, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.CreateProductIn) uint32); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(uint32)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, usecase.CreateProductIn) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockproductUsecase_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type MockproductUsecase_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - in usecase.CreateProductIn
func (_e *MockproductUsecase_Expecter) CreateProduct(ctx interface{}, in interface{}) *MockproductUsecase_CreateProduct_Call {
	return &MockproductUsecase_CreateProduct_Call{Call: _e.mock.On("CreateProduct", ctx, in)}
}

func (_c *MockproductUsecase_CreateProduct_Call) Run(run func(ctx context.Context, in usecase.CreateProductIn)) *MockproductUsecase_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecase.CreateProductIn
		if args[1] != nil {
			arg1 = args[1].(usecase.CreateProductIn)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockproductUsecase_CreateProduct_Call) Return(v uint32, err error) *MockproductUsecase_CreateProduct_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockproductUsecase_CreateProduct_Call) RunAndReturn(run func(ctx context.Context, in usecase.CreateProductIn) (uint32, error)) *MockproductUsecase_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProduct provides a mock function for the type MockproductUsecase
func (_mock *MockproductUsecase) DeleteProduct(ctx context.Context, id uint32) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockproductUsecase_DeleteProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProduct'
type MockproductUsecase_DeleteProduct_Call struct {
	*mock.Call
}

// DeleteProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint32
func (_e *MockproductUsecase_Expecter) DeleteProduct(ctx interface{}, id interface{}) *MockproductUsecase_DeleteProduct_Call {
	return &MockproductUsecase_DeleteProduct_Call{Call: _e.mock.On("DeleteProduct", ctx, id)}
}

func (_c *MockproductUsecase_DeleteProduct_Call) Run(run func(ctx context.Context, id uint32)) *MockproductUsecase_DeleteProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockproductUsecase_DeleteProduct_Call) Return(err error) *MockproductUsecase_DeleteProduct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockproductUsecase_DeleteProduct_Call) RunAndReturn(run func(ctx context.Context, id uint32) error) *MockproductUsecase_DeleteProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductByID provides a mock function for the type MockproductUsecase
func (_mock *MockproductUsecase) GetProductByID(ctx context.Context, id uint32) (models.Product, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 models.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32) (models.Product, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32) models.Product); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Product)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockproductUsecase_GetProductByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductByID'
type MockproductUsecase_GetProductByID_Call struct {
	*mock.Call
}

// GetProductByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint32
func (_e *MockproductUsecase_Expecter) GetProductByID(ctx interface{}, id interface{}) *MockproductUsecase_GetProductByID_Call {
	return &MockproductUsecase_GetProductByID_Call{Call: _e.mock.On("GetProductByID", ctx, id)}
}

func (_c *MockproductUsecase_GetProductByID_Call) Run(run func(ctx context.Context, id uint32)) *MockproductUsecase_GetProductByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockproductUsecase_GetProductByID_Call) Return(product models.Product, err error) *MockproductUsecase_GetProductByID_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockproductUsecase_GetProductByID_Call) RunAndReturn(run func(ctx context.Context, id uint32) (models.Product, error)) *MockproductUsecase_GetProductByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetProducts provides a mock function for the type MockproductUsecase
func (_mock *MockproductUsecase) GetProducts(ctx context.Context, in usecase.GetProductsIn) ([]models.Product, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for GetProducts")
	}

	var r0 []models.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.GetProductsIn) ([]models.Product, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.GetProductsIn) []models.Product); ok {
		r0 = returnFunc(ctx, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, usecase.GetProductsIn) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockproductUsecase_GetProducts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProducts'
type MockproductUsecase_GetProducts_Call struct {
	*mock.Call
}

// GetProducts is a helper method to define mock.On call
//   - ctx context.Context
//   - in usecase.GetProductsIn
func (_e *MockproductUsecase_Expecter) GetProducts(ctx interface{}, in interface{}) *MockproductUsecase_GetProducts_Call {
	return &MockproductUsecase_GetProducts_Call{Call: _e.mock.On("GetProducts", ctx, in)}
}

func (_c *MockproductUsecase_GetProducts_Call) Run(run func(ctx context.Context, in usecase.GetProductsIn)) *MockproductUsecase_GetProducts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecase.GetProductsIn
		if args[1] != nil {
			arg1 = args[1].(usecase.GetProductsIn)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockproductUsecase_GetProducts_Call) Return(products []models.Product, err error) *MockproductUsecase_GetProducts_Call {
	_c.Call.Return(products, err)
	return _c
}

func (_c *MockproductUsecase_GetProducts_Call) RunAndReturn(run func(ctx context.Context, in usecase.GetProductsIn) ([]models.Product, error)) *MockproductUsecase_GetProducts_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProduct provides a mock function for the type MockproductUsecase
func (_mock *MockproductUsecase) UpdateProduct(ctx context.Context, id uint32, in usecase.UpdateProductIn) error {
	ret := _mock.Called(ctx, id, in)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint32, usecase.UpdateProductIn) error); ok {
		r0 = returnFunc(ctx, id, in)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockproductUsecase_UpdateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProduct'
type MockproductUsecase_UpdateProduct_Call struct {
	*mock.Call
}

// UpdateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint32
//   - in usecase.UpdateProductIn
func (_e *MockproductUsecase_Expecter) UpdateProduct(ctx interface{}, id interface{}, in interface{}) *MockproductUsecase_UpdateProduct_Call {
	return &MockproductUsecase_UpdateProduct_Call{Call: _e.mock.On("UpdateProduct", ctx, id, in)}
}

func (_c *MockproductUsecase_UpdateProduct_Call) Run(run func(ctx context.Context, id uint32, in usecase.UpdateProductIn)) *MockproductUsecase_UpdateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		var arg2 usecase.UpdateProductIn
		if args[2] != nil {
			arg2 = args[2].(usecase.UpdateProductIn)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockproductUsecase_UpdateProduct_Call) Return(err error) *MockproductUsecase_UpdateProduct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockproductUsecase_UpdateProduct_Call) RunAndReturn(run func(ctx context.Context, id uint32, in usecase.UpdateProductIn) error) *MockproductUsecase_UpdateProduct_Call {
	_c.Call.Return(run)
	return _c
}
