// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"iTcatt/orders/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockproductRepo creates a new instance of MockproductRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockproductRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockproductRepo {
	mock := &MockproductRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockproductRepo is an autogenerated mock type for the productRepo type
type MockproductRepo struct {
	mock.Mock
}

type MockproductRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockproductRepo) EXPECT() *MockproductRepo_Expecter {
	return &MockproductRepo_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockproductRepo
func (_mock *MockproductRepo) GetByID(ctx context.Context, id string) (models.Product, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 models.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.Product, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.Product); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Product)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockproductRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockproductRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockproductRepo_Expecter) GetByID(ctx interface{}, id interface{}) *MockproductRepo_GetByID_Call {
	return &MockproductRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockproductRepo_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockproductRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockproductRepo_GetByID_Call) Return(product models.Product, err error) *MockproductRepo_GetByID_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockproductRepo_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (models.Product, error)) *MockproductRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
