// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockobjectStore creates a new instance of MockobjectStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockobjectStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockobjectStore {
	mock := &MockobjectStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockobjectStore is an autogenerated mock type for the objectStore type
type MockobjectStore struct {
	mock.Mock
}

type MockobjectStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockobjectStore) EXPECT() *MockobjectStore_Expecter {
	return &MockobjectStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockobjectStore
func (_mock *MockobjectStore) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockobjectStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockobjectStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockobjectStore_Expecter) Delete(ctx interface{}, key interface{}) *MockobjectStore_Delete_Call {
	return &MockobjectStore_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockobjectStore_Delete_Call) Run(run func(ctx context.Context, key string)) *MockobjectStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockobjectStore_Delete_Call) Return(err error) *MockobjectStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockobjectStore_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockobjectStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// URL provides a mock function for the type MockobjectStore
func (_mock *MockobjectStore) URL(key string) string {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for URL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockobjectStore_URL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'URL'
type MockobjectStore_URL_Call struct {
	*mock.Call
}

// URL is a helper method to define mock.On call
//   - key string
func (_e *MockobjectStore_Expecter) URL(key interface{}) *MockobjectStore_URL_Call {
	return &MockobjectStore_URL_Call{Call: _e.mock.On("URL", key)}
}

func (_c *MockobjectStore_URL_Call) Run(run func(key string)) *MockobjectStore_URL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockobjectStore_URL_Call) Return(s string) *MockobjectStore_URL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockobjectStore_URL_Call) RunAndReturn(run func(key string) string) *MockobjectStore_URL_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type MockobjectStore
func (_mock *MockobjectStore) Upload(ctx context.Context, key string, r io.Reader, size int64, contentType string) error {
	ret := _mock.Called(ctx, key, r, size, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, string) error); ok {
		r0 = returnFunc(ctx, key, r, size, contentType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockobjectStore_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockobjectStore_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - r io.Reader
//   - size int64
//   - contentType string
func (_e *MockobjectStore_Expecter) Upload(ctx interface{}, key interface{}, r interface{}, size interface{}, contentType interface{}) *MockobjectStore_Upload_Call {
	return &MockobjectStore_Upload_Call{Call: _e.mock.On("Upload", ctx, key, r, size, contentType)}
}

func (_c *MockobjectStore_Upload_Call) Run(run func(ctx context.Context, key string, r io.Reader, size int64, contentType string)) *MockobjectStore_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 io.Reader
		if args[2] != nil {
			arg2 = args[2].(io.Reader)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockobjectStore_Upload_Call) Return(err error) *MockobjectStore_Upload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockobjectStore_Upload_Call) RunAndReturn(run func(ctx context.Context, key string, r io.Reader, size int64, contentType string) error) *MockobjectStore_Upload_Call {
	_c.Call.Return(run)
	return _c
}
