// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"iTcatt/orders/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockimageRepo creates a new instance of MockimageRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockimageRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockimageRepo {
	mock := &MockimageRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockimageRepo is an autogenerated mock type for the imageRepo type
type MockimageRepo struct {
	mock.Mock
}

type MockimageRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockimageRepo) EXPECT() *MockimageRepo_Expecter {
	return &MockimageRepo_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockimageRepo
func (_mock *MockimageRepo) Count(ctx context.Context, productID string) (int, error) {
	ret := _mock.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(ctx, productID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, productID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockimageRepo_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockimageRepo_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
//   - productID string
func (_e *MockimageRepo_Expecter) Count(ctx interface{}, productID interface{}) *MockimageRepo_Count_Call {
	return &MockimageRepo_Count_Call{Call: _e.mock.On("Count", ctx, productID)}
}

func (_c *MockimageRepo_Count_Call) Run(run func(ctx context.Context, productID string)) *MockimageRepo_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockimageRepo_Count_Call) Return(n int, err error) *MockimageRepo_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockimageRepo_Count_Call) RunAndReturn(run func(ctx context.Context, productID string) (int, error)) *MockimageRepo_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockimageRepo
func (_mock *MockimageRepo) Create(ctx context.Context, img models.Image) error {
	ret := _mock.Called(ctx, img)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.Image) error); ok {
		r0 = returnFunc(ctx, img)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockimageRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockimageRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - img models.Image
func (_e *MockimageRepo_Expecter) Create(ctx interface{}, img interface{}) *MockimageRepo_Create_Call {
	return &MockimageRepo_Create_Call{Call: _e.mock.On("Create", ctx, img)}
}

func (_c *MockimageRepo_Create_Call) Run(run func(ctx context.Context, img models.Image)) *MockimageRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.Image
		if args[1] != nil {
			arg1 = args[1].(models.Image)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockimageRepo_Create_Call) Return(err error) *MockimageRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockimageRepo_Create_Call) RunAndReturn(run func(ctx context.Context, img models.Image) error) *MockimageRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockimageRepo
func (_mock *MockimageRepo) Delete(ctx context.Context, imageID string) error {
	ret := _mock.Called(ctx, imageID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, imageID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockimageRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockimageRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID string
func (_e *MockimageRepo_Expecter) Delete(ctx interface{}, imageID interface{}) *MockimageRepo_Delete_Call {
	return &MockimageRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, imageID)}
}

func (_c *MockimageRepo_Delete_Call) Run(run func(ctx context.Context, imageID string)) *MockimageRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockimageRepo_Delete_Call) Return(err error) *MockimageRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockimageRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, imageID string) error) *MockimageRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockimageRepo
func (_mock *MockimageRepo) Get(ctx context.Context, imageID string) (models.Image, error) {
	ret := _mock.Called(ctx, imageID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 models.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.Image, error)); ok {
		return returnFunc(ctx, imageID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.Image); ok {
		r0 = returnFunc(ctx, imageID)
	} else {
		r0 = ret.Get(0).(models.Image)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, imageID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockimageRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockimageRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - imageID string
func (_e *MockimageRepo_Expecter) Get(ctx interface{}, imageID interface{}) *MockimageRepo_Get_Call {
	return &MockimageRepo_Get_Call{Call: _e.mock.On("Get", ctx, imageID)}
}

func (_c *MockimageRepo_Get_Call) Run(run func(ctx context.Context, imageID string)) *MockimageRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockimageRepo_Get_Call) Return(image models.Image, err error) *MockimageRepo_Get_Call {
	_c.Call.Return(image, err)
	return _c
}

func (_c *MockimageRepo_Get_Call) RunAndReturn(run func(ctx context.Context, imageID string) (models.Image, error)) *MockimageRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByProductID provides a mock function for the type MockimageRepo
func (_mock *MockimageRepo) GetByProductID(ctx context.Context, productID string) ([]models.Image, error) {
	ret := _mock.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetByProductID")
	}

	var r0 []models.Image
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]models.Image, error)); ok {
		return returnFunc(ctx, productID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []models.Image); ok {
		r0 = returnFunc(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Image)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockimageRepo_GetByProductID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByProductID'
type MockimageRepo_GetByProductID_Call struct {
	*mock.Call
}

// GetByProductID is a helper method to define mock.On call
//   - ctx context.Context
//   - productID string
func (_e *MockimageRepo_Expecter) GetByProductID(ctx interface{}, productID interface{}) *MockimageRepo_GetByProductID_Call {
	return &MockimageRepo_GetByProductID_Call{Call: _e.mock.On("GetByProductID", ctx, productID)}
}

func (_c *MockimageRepo_GetByProductID_Call) Run(run func(ctx context.Context, productID string)) *MockimageRepo_GetByProductID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockimageRepo_GetByProductID_Call) Return(images []models.Image, err error) *MockimageRepo_GetByProductID_Call {
	_c.Call.Return(images, err)
	return _c
}

func (_c *MockimageRepo_GetByProductID_Call) RunAndReturn(run func(ctx context.Context, productID string) ([]models.Image, error)) *MockimageRepo_GetByProductID_Call {
	_c.Call.Return(run)
	return _c
}
