// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMocktxManager creates a new instance of MocktxManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocktxManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocktxManager {
	mock := &MocktxManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MocktxManager is an autogenerated mock type for the txManager type
type MocktxManager struct {
	mock.Mock
}

type MocktxManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MocktxManager) EXPECT() *MocktxManager_Expecter {
	return &MocktxManager_Expecter{mock: &_m.Mock}
}

// RunInTx provides a mock function for the type MocktxManager
func (_mock *MocktxManager) RunInTx(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for RunInTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MocktxManager_RunInTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunInTx'
type MocktxManager_RunInTx_Call struct {
	*mock.Call
}

// RunInTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *MocktxManager_Expecter) RunInTx(ctx interface{}, fn interface{}) *MocktxManager_RunInTx_Call {
	return &MocktxManager_RunInTx_Call{Call: _e.mock.On("RunInTx", ctx, fn)}
}

func (_c *MocktxManager_RunInTx_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *MocktxManager_RunInTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MocktxManager_RunInTx_Call) Return(err error) *MocktxManager_RunInTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MocktxManager_RunInTx_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *MocktxManager_RunInTx_Call {
	_c.Call.Return(run)
	return _c
}
